name: next-shopify-storefront-demo

on:
  # push:
  #   tags:
  #     - "v*"
  workflow_dispatch:
    inputs:
      environment:
        description: "Env deploy to"
        required: false
        type: choice
        options: ["development", "production"]
        default: "development"
      node_version:
        description: "Node version"
        required: false
        type: choice
        options: ["lts-alpine", "22-alpine", "24-alpine", "25-alpine"]
        default: "lts-alpine"

permissions:
  contents: read
  packages: write
  id-token: write
# Stops workflow if there is a newer workflow pending
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  node-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Extract version from tag
        id: version-extract
        uses: damienaicheh/extract-version-from-tag-action@v1.3.0

      - name: Set outputs
        id: version
        run: |
          echo "major=$MAJOR" >> $GITHUB_OUTPUT
          echo "minor=$MINOR" >> $GITHUB_OUTPUT
          echo "patch=$PATCH" >> $GITHUB_OUTPUT

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}-${{ inputs.environment }}
          # tags: |
          #   type=semver,pattern={{version}}
          #   type=semver,pattern={{major}}.{{minor}}
          #   type=semver,pattern={{major}}
          #   type=raw,value=latest

      - name: Build Docker Image
        uses: docker/build-push-action@v7.1.0
        with:
          tags: |
            ghcr.io/${{ github.repository }}-${{ inputs.environment }}:${{ steps.version.outputs.major }}
            ghcr.io/${{ github.repository }}-${{ inputs.environment }}:${{ steps.version.outputs.major }}-${{ inputs.node_version }}
            ghcr.io/${{ github.repository }}-${{ inputs.environment }}:${{ steps.version.outputs.major }}.${{ steps.version.outputs.minor }}
            ghcr.io/${{ github.repository }}-${{ inputs.environment }}:${{ steps.version.outputs.major }}.${{ steps.version.outputs.minor }}-${{ inputs.node_version }}
            ghcr.io/${{ github.repository }}-${{ inputs.environment }}:${{ steps.version.outputs.major }}.${{ steps.version.outputs.minor }}.${{ steps.version.outputs.patch }}
            ghcr.io/${{ github.repository }}-${{ inputs.environment }}:${{ steps.version.outputs.major }}.${{ steps.version.outputs.minor }}.${{ steps.version.outputs.patch }}-${{ inputs.node_version }}
            ghcr.io/${{ github.repository }}-${{ inputs.environment }}:latest
            ghcr.io/${{ github.repository }}-${{ inputs.environment }}:${{ github.sha }}
          # tags: ${{ steps.meta.outputs.tags }}
          push: true
          labels: |
            com.panik.sha=${{ github.sha }}
            ${{ steps.meta.outputs.labels }}
          # List of metadata for an image
          # labels: |
          #   org.opencontainers.image.source "ghcr.io/${{ github.repository }}"
          #   org.opencontainers.image.version "${{ steps.version.outputs.major }}.${{ steps.version.outputs.minor }}.${{ steps.version.outputs.patch }}"
          #   com.panik.sha "${{ github.sha }}"

          # # List of annotation to set to the image
          # annotations: # optional
          # # List of attestation parameters (e.g., type=sbom,generator=image)
          # build-args: # optional
          # # List of additional build contexts (e.g., name=path)
          # build-contexts: # optional
          # # List of target platforms for build
          # platforms: # optional
          # # Generate SBOM attestation for the build (shorthand for --attest=type=sbom)
          # sbom: # optional
          # # List of secrets to expose to the build (e.g., key=string, GIT_AUTH_TOKEN=mytoken)
          # secrets: # optional
          # # List of secret env vars to expose to the build (e.g., key=envname, MY_SECRET=MY_ENV_VAR)
          # secret-envs: # optional
          # # List of secret files to expose to the build (e.g., key=filename, MY_SECRET=./secret.txt)
          # secret-files: # optional
          # # Sets the target stage to build
          target: ${{ inputs.environment }}
